mtw.routing.test.app/Models/ErrorViewModel.cs
using System;

namespace mtw.routing.test.app.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mtw.routing.test.app/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using mtw.routing.test.app.Models;

namespace mtw.routing.test.app.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private Counter _counter;
        IConfiguration _config;

        public HomeController(ILogger<HomeController> logger, IConfiguration config, IMemoryCache cache)
        {
            var counter = cache.GetOrCreate("counter", entry =>
             {
                 return new Counter();
             });

            _counter = counter;
            _config = config;
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.AppName = _config["AppName"];
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mtw.routing.test.app/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;

namespace mtw.routing.test.app.Controllers
{
    [Route("login")]
    public class LoginController : Controller
    {
        private Counter _counter;
        IConfiguration _config;

        public LoginController(IConfiguration config, IMemoryCache cache)
        {
            var counter = cache.GetOrCreate("counter", entry =>
            {
                return new Counter();
            });

            _counter = counter;
            _config = config;
        }

        public IActionResult Index()
        {
            string parsedParams = string.Empty;

            foreach (var key in HttpContext.Request.Query.Keys)
            {
                parsedParams += key + ":" + HttpContext.Request.Query[key] + ",";
            }

            string parsedHeaders = string.Empty;

            foreach(var header in HttpContext.Request.Headers.Keys)
            {
              parsedHeaders += "    " + header + ": " + HttpContext.Request.Headers[header] + "\n";
            }

            ViewBag.Count = _counter.GetCount();
            ViewBag.EncodedUrl = HttpContext.Request.GetEncodedUrl();
            ViewBag.DisplayUrl = HttpContext.Request.GetDisplayUrl();
            ViewBag.Query = HttpContext.Request.QueryString;
            ViewBag.QueryParams = parsedParams;
            ViewBag.Headers = parsedHeaders;
            ViewBag.AppName = _config["AppName"];
            ViewBag.Color = _config["Color"];
            return View();
        }
    }
}

mtw.routing.test.app/Controllers/MyCarMaxController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;

namespace mtw.routing.test.app.Controllers
{
    [Route("mycarmax/sign-in")]
    public class MyCarMaxController : Controller
    {
        private Counter _counter;
        IConfiguration _config;

        public MyCarMaxController(IConfiguration config, IMemoryCache cache)
        {
            var counter = cache.GetOrCreate("counter", entry =>
            {
                return new Counter();
            });

            _counter = counter;
            _config = config;
        }

        // GET: MyCarMaxController
        public ActionResult Index()
        {
            string parsedParams = string.Empty;
            foreach (var key in HttpContext.Request.Query.Keys)
            {
                parsedParams += key + ":" + HttpContext.Request.Query[key] + ",";
            }

            string parsedHeaders = string.Empty;

            foreach(var header in HttpContext.Request.Headers.Keys)
            {
              parsedHeaders += "    " + header + ": " + HttpContext.Request.Headers[header] + "\n";
            }

            ViewBag.AppName = _config["AppName"];
            ViewBag.Count = _counter.GetCount();
            ViewBag.Color = _config["Color"];
            ViewBag.EncodedUrl = HttpContext.Request.GetEncodedUrl();
            ViewBag.DisplayUrl = HttpContext.Request.GetDisplayUrl();
            ViewBag.Query = HttpContext.Request.QueryString;
            ViewBag.QueryParams = parsedParams;
            ViewBag.Headers = parsedHeaders;
            return View();
        }
    }
}

mtw.routing.test.app/Controllers/ResetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;

namespace mtw.routing.test.app.Controllers
{
    [Route("reset")]
    public class ResetController : Controller
    {
        private Counter _counter;
        IConfiguration _config;

        public ResetController(IConfiguration config, IMemoryCache cache)
        {
            var counter = cache.GetOrCreate("counter", entry =>
            {
                return new Counter();
            });

            _counter = counter;
            _config = config;
        }

        public IActionResult Index()
        {
            _counter.Reset();
            return View();
        }
    }
}

mtw.routing.test.app/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Default Home Page for @ViewBag.AppName</h1>
</div>

mtw.routing.test.app/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 style="color: @ViewBag.Color">LOGIN Page for @ViewBag.AppName</h1>
<div>Count: @ViewBag.Count</div>
<div>Display URL: @ViewBag.DisplayUrl</div>
<div>Encoded URL: @ViewBag.EncodedUrl</div>
<div>Query: @ViewBag.Query</div>
<div>Query Parameters: @ViewBag.QueryParams</div>
<div>Headers: <pre>@ViewBag.Headers</pre></div>

mtw.routing.test.app/Views/MyCarMax/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 style="color: @ViewBag.Color">MyCarMax Sign In Page for @ViewBag.AppName</h1>
<div>Count: @ViewBag.Count</div>
<div>Display URL: @ViewBag.DisplayUrl</div>
<div>Encoded URL: @ViewBag.EncodedUrl</div>
<div>Query: @ViewBag.Query</div>
<div>Query Parameters: @ViewBag.QueryParams</div>
<div>Headers: <pre>@ViewBag.Headers</pre></div>

mtw.routing.test.app/Views/Reset/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

mtw.routing.test.app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mtw.routing.test.app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mtw.routing.test.app</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyCarMax" asp-action="Index">Sign-In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reset" asp-action="Index">Reset</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - mtw.routing.test.app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>